name: Autograding Tests

on:
  - push
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 'latest'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run unittest tests
      id: run-test-cases
      run: |
        python -m unittest tests/test_fundamentals.py

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        RUN-TEST-CASES_RESULTS: "${{steps.run-test-cases.outputs.result}}"
      with:
        runners: run-test-cases
